---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8s-fluxcd
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/cluster1/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-fluxcd
